export const GET_DOGS = "GET_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_DOG_BY_NAME = "GET_DOG_BY_NAME";
export const GET_DOG_DETAILS = "GET_DOG_DETAILS";
export const CREATE_DOG = "CREATE_DOG";
export const FILTER_DOGS_BY_TEMPERAMENT_AND_CREATED =
	"FILTER_DOGS_BY_TEMPERAMENT_AND_CREATED";
export const ORDER_DOGS_BY_NAME = "ORDER_DOGS_BY_NAME";
export const ORDER_DOGS_BY_WEIGHT = "ORDER_DOGS_BY_WEIGHT";
export const CLEAN_STATE = "CLEAN_STATE";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_CURRENT_SEARCH = "SET_CURRENT_SEARCH";
export const SET_CURRENT_FILTER_BY_TEMPERAMENT =
	"SET_CURRENT_FILTER_BY_TEMPERAMENT";
export const SET_CURRENT_ORDER_BY_NAME = "SET_CURRENT_ORDER_BY_NAME";
export const SET_CURRENT_ORDER_BY_WEIGHT = "SET_CURRENT_ORDER_BY_WEIGHT";
export const SET_CURRENT_FILTER_BY_CREATED = "SET_CURRENT_FILTER_BY_CREATED";
export const RESET_STATE = "RESET_STATE";
export const RESET_FILTERS_AND_ORDER = "RESET_FILTERS_AND_ORDER";
